### PR TITLE
Support iseq

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
Support iseq

How to install:
1. trial and error

How to test:
1. cgstats add --machine iseq --unaligned Unaligned-Y30I10I10 /home/hiseq.clinical/iseq/demux//20190528_FS10000534_7_BPC29611-3324

Expected outcome:
- [x] new entry in database
- [x] flowcell name is BPC29611-3324
- [x] pos is 'A'
- [x] hiseqtype is 'iseq'
- [x] stuffs looking ok

This is a minor since we only add new func without changing the old

- [x] R @ingkebil 
- [x] T @emiliaol @patrikgrenfeldt 
- [x] D @ingkebil

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
@emiliaol @ingkebil could you have a look at this code and point out where it needs changes?

**Comment by patrikgrenfeldt** [comment]
Test result:
New entry in database:
image
🆗 
Name is BPC29611-3324:
image
🚫 
pos is 'A': 🆗  
hiseqtype is 'iseq': 🆗 
stuffs looking ok: 🆗

**Comment by patrikgrenfeldt** [comment]
FC Name: 🆗 
image

**Comment by ingkebil** [comment]
The tests are failing for both py2 and py3 :o 

Do you have time to have a look @patrikgrenfeldt ?

**Comment by patrikgrenfeldt** [comment]
> 
> 
> The tests are failing for both py2 and py3 :o
> 
> Do you have time to have a look @patrikgrenfeldt ?

Sure thing

**Comment by patrikgrenfeldt** [comment]
> 
> 
> The tests are failing for both py2 and py3 :o
> 
> Do you have time to have a look @patrikgrenfeldt ?

@ingkebil I'm pretty sure the answer is [here](https://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql), I just don't understand how to apply in our [test_select ](https://github.com/Clinical-Genomics/cgstats/blob/fa06ae6b922368c2b14f1c56c54bc3aa8b314cb8/tests/cgstats/db/test_db.py#L79). Do you have any idea?

**Comment by ingkebil** [comment]
deployed

**Comment by patrikgrenfeldt** [comment]
Resolves #20

**Pull request merged**
