### PR TITLE
no more usage of basemask in novaseqparse.py

### PR DESCRIPTION
**Pull request by karlnyr**
### This PR updates:
- Novaseqparse to work without  basemask

**How to prepare for test**:
- [x] `ssh` to hasta
- [x] Activate stage `S_demux`
- [x] Install on stage: 
`pip install -U git+https://github.com/Clinical-Genomics/cgstats@no_more_basemask_novaseq`

### How to test:
- [x] Test to add a novaseq flowcell to cgstats
- [x] Verify the supportparameters table is correctly filled in

### Expected outcome:
- [x] Structure of table is maintained

### Review:
- [ ] Code approved by
- [x] Tests executed by @karlnyr 
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by karlnyr** [comment]
Installing on stage:
image

Storing a FC:
image

Checking entry of FC in supportparams:

```sql
SELECT * FROM `cgstats-stage`.supportparams where document_path like "%HW72JDRXX%"
'2710','/home/proj/stage/demultiplexed-runs/201214_A00689_0204_AHW72JDRXX/Unaligned',NULL,NULL,NULL,NULL,'bcl2fastq v2.20.0.422','/home/proj/production/demux-on-hasta/novaseq/container/bcl2fastq_v2-20-0.sif','bcl2fastq --loading-threads 3 --processing-threads 15 --writing-threads 3 --runfolder-dir /home/proj/stage/flowcells/novaseq/runs//201214_A00689_0204_AHW72JDRXX --output-dir /home/proj/stage/demultiplexed-runs//201214_A00689_0204_AHW72JDRXX/Unaligned --sample-sheet /home/proj/stage/flowcells/novaseq/runs//201214_A00689_0204_AHW72JDRXX/SampleSheet.csv --barcode-mismatches 1','/home/proj/stage/demultiplexed-runs/201214_A00689_0204_AHW72JDRXX/Unaligned/SampleSheet.csv','[Data]\nFCID,Lane,SampleID,SampleRef,index,index2,SampleName,Control,Recipe,Operator,Project\nHW72JDRXX,1,2020-26636-05,,CTACGAAG,CTGTCGAG,269990,,,,269990\nHW72JDRXX,1,2020-26657-05,,CTTAATAC,CACAATGG,269990,,,,269990\nHW72JDRXX,1,2020-26658-05,,CTTATGAA,ACATTGGC,269990,,,,269990\nHW72JDRXX,1,2020-26678-05,,CTATCATT,AGGTGGTC,269990,,,,269990\nHW72JDRXX,1,2020-26681-05,,CTGGAAGC,TCTGCACC,269990,,,,269990\nHW72JDRXX,1,2020-26757-05,,CAACCGTG,CGTGAGAG,269990,,,,269990\nHW72JDRXX,1,2020-26776-05,,TGAGGCGC,TGGTCTCC,269990,,,,269990\nHW72JDRXX,1,2020-26783-05,,AAGTACAG,GACGTGAC,269990,,,,269990\nHW72JDRXX,1,2020-26876-05,,GATGCGTC,GCAGCCTC,269990,,,,269990\nHW72JDRXX,1,2020-26877-05,,GAAGTCTT,ACCGTAGT,269990,,,,269990\nHW72JDRXX,1,2020-26879-05,,TCGGCACC,GACGTTGG,269990,,,,269990\nHW72JDRXX,1,2020-26923-05,,CGCGCCAA,CCTAGCCA,269990,,,,269990\nHW72JDRXX,1,2020-26926-05,,CGTAAGAG,GTCAGCGA,269990,,,,269990\nHW72JDRXX,1,2020-26929-05,,TGGTGCAC,GTGATTCC,269990,,,,269990\nHW72JDRXX,1,2020-26973-05,,CAGGTTCC,GGTGTTCG,269990,,,,269990\nHW72JDRXX,1,2020-26974-05,,CCGTGCCA,GGAGCTGC,269990,,,,269990\nHW72JDRXX,1,2020-26975-05,,CTACGGCA,CTACGAGG,269990,,,,269990\nHW72JDRXX,1,2020-27008-05,,GAAGAGGC,TAGCACTT,269990,,,,269990\nHW72JDRXX,1,2020-27102-05,,AAGAAGCG,TTATCTAC,269990,,,,269990\nHW72JDRXX,1,2020-27110-05,,CGAACGGA,CCGGTAGG,269990,,,,269990\nHW72JDRXX,1,2020-27119-05,,AAGAGAGC,ACTGGCTG,269990,,,,269990\nHW72JDRXX,1,2020-27120-05,,CCACAATG,CGTCAACG,269990,,,,269990\nHW72JDRXX,1,2020-27125-05,,TGAACAGG,TTGTTCTC,269990,,,,269990\nHW72JDRXX,1,2020-27146-05,,GATTCCTT,TGCCTATG,269990,,,,269990\nHW72JDRXX,1,2020-27242-05,,CGGATAAC,CGTTCGGC,269990,,,,269990\nHW72JDRXX,1,2020-27266-05,,CTCACGAT,GCCGTAAG,269990,,,,269990\nHW72JDRXX,1,2020-27380-05,,CTACTGAC,CATCCTCC,269990,,,,269990\nHW72JDRXX,1,2020-27386-05,,TCAACGAG,GGTTGACG,269990,,,,269990\nHW72JDRXX,1,2020-27393-04,,TGTGTGCC,ACCTGATG,269990,,,,269990\nHW72JDRXX,1,2020-27397-05,,CAGTGTGG,GATTCACA,269990,,,,269990\nHW72JDRXX,1,2020-27426-05,,TTACCTGG,GCAATCGT,269990,,,,269990\nHW72JDRXX,1,2020-27471-05,,CTACTCGA,GTTCATCT,269990,,,,269990\nHW72JDRXX,1,2020-27536-05,,GAATCTGG,CGTGGACA,269990,,,,269990\nHW72JDRXX,1,2020-27541-05,,TCGGTCGA,GCACTTGG,269990,,,,269990\nHW72JDRXX,1,2020-27545-05,,TCTTAAGT,ATTCAGCG,269990,,,,269990\nHW72JDRXX,1,2020-27553-05,,TGCGAGAC,TCGCCGGC,269990,,,,269990\nHW72JDRXX,1,2020-27611-05,,CACCACGG,TTACAACG,269990,,,,269990\nHW72JDRXX,1,2020-27633-05,,TTCCACCA,CCTTAACC,269990,,,,269990\nHW72JDRXX,1,2020-27634-05,,CTGCAACG,CGAATGTC,269990,,,,269990\nHW72JDRXX,1,2020-27636-05,,GATTCGAG,ATACTCGG,269990,,,,269990\nHW72JDRXX,1,2020-27668-05,,CTGATTGA,AGTGTGTC,269990,,,,269990\nHW72JDRXX,1,2020-27669-05,,TCGGTAAG,TGAGTTAG,269990,,,,269990\nHW72JDRXX,1,2020-27671-05,,TTAGAGTC,TCGTCACA,269990,,,,269990\nHW72JDRXX,1,2020-27710-05,,CCTGGTGT,CCGGAGGC,269990,,,,269990\nHW72JDRXX,1,2020-27725-05,,TGTGTTAA,ACCGTGCC,269990,,,,269990\nHW72JDRXX,1,2020-27726-05,,CCGCTGTT,TGCGGTCT,269990,,,,269990\nHW72JDRXX,2,2020-26636-05,,CTACGAAG,CTGTCGAG,269990,,,,269990\nHW72JDRXX,2,2020-26657-05,,CTTAATAC,CACAATGG,269990,,,,269990\nHW72JDRXX,2,2020-26658-05,,CTTATGAA,ACATTGGC,269990,,,,269990\nHW72JDRXX,2,2020-26678-05,,CTATCATT,AGGTGGTC,269990,,,,269990\nHW72JDRXX,2,2020-26681-05,,CTGGAAGC,TCTGCACC,269990,,,,269990\nHW72JDRXX,2,2020-26757-05,,CAACCGTG,CGTGAGAG,269990,,,,269990\nHW72JDRXX,2,2020-26776-05,,TGAGGCGC,TGGTCTCC,269990,,,,269990\nHW72JDRXX,2,2020-26783-05,,AAGTACAG,GACGTGAC,269990,,,,269990\nHW72JDRXX,2,2020-26876-05,,GATGCGTC,GCAGCCTC,269990,,,,269990\nHW72JDRXX,2,2020-26877-05,,GAAGTCTT,ACCGTAGT,269990,,,,269990\nHW72JDRXX,2,2020-26879-05,,TCGGCACC,GACGTTGG,269990,,,,269990\nHW72JDRXX,2,2020-26923-05,,CGCGCCAA,CCTAGCCA,269990,,,,269990\nHW72JDRXX,2,2020-26926-05,,CGTAAGAG,GTCAGCGA,269990,,,,269990\nHW72JDRXX,2,2020-26929-05,,TGGTGCAC,GTGATTCC,269990,,,,269990\nHW72JDRXX,2,2020-26973-05,,CAGGTTCC,GGTGTTCG,269990,,,,269990\nHW72JDRXX,2,2020-26974-05,,CCGTGCCA,GGAGCTGC,269990,,,,269990\nHW72JDRXX,2,2020-26975-05,,CTACGGCA,CTACGAGG,269990,,,,269990\nHW72JDRXX,2,2020-27008-05,,GAAGAGGC,TAGCACTT,269990,,,,269990\nHW72JDRXX,2,2020-27102-05,,AAGAAGCG,TTATCTAC,269990,,,,269990\nHW72JDRXX,2,2020-27110-05,,CGAACGGA,CCGGTAGG,269990,,,,269990\nHW72JDRXX,2,2020-27119-05,,AAGAGAGC,ACTGGCTG,269990,,,,269990\nHW72JDRXX,2,2020-27120-05,,CCACAATG,CGTCAACG,269990,,,,269990\nHW72JDRXX,2,2020-27125-05,,TGAACAGG,TTGTTCTC,269990,,,,269990\nHW72JDRXX,2,2020-27146-05,,GATTCCTT,TGCCTATG,269990,,,,269990\nHW72JDRXX,2,2020-27242-05,,CGGATAAC,CGTTCGGC,269990,,,,269990\nHW72JDRXX,2,2020-27266-05,,CTCACGAT,GCCGTAAG,269990,,,,269990\nHW72JDRXX,2,2020-27380-05,,CTACTGAC,CATCCTCC,269990,,,,269990\nHW72JDRXX,2,2020-27386-05,,TCAACGAG,GGTTGACG,269990,,,,269990\nHW72JDRXX,2,2020-27393-04,,TGTGTGCC,ACCTGATG,269990,,,,269990\nHW72JDRXX,2,2020-27397-05,,CAGTGTGG,GATTCACA,269990,,,,269990\nHW72JDRXX,2,2020-27426-05,,TTACCTGG,GCAATCGT,269990,,,,269990\nHW72JDRXX,2,2020-27471-05,,CTACTCGA,GTTCATCT,269990,,,,269990\nHW72JDRXX,2,2020-27536-05,,GAATCTGG,CGTGGACA,269990,,,,269990\nHW72JDRXX,2,2020-27541-05,,TCGGTCGA,GCACTTGG,269990,,,,269990\nHW72JDRXX,2,2020-27545-05,,TCTTAAGT,ATTCAGCG,269990,,,,269990\nHW72JDRXX,2,2020-27553-05,,TGCGAGAC,TCGCCGGC,269990,,,,269990\nHW72JDRXX,2,2020-27611-05,,CACCACGG,TTACAACG,269990,,,,269990\nHW72JDRXX,2,2020-27633-05,,TTCCACCA,CCTTAACC,269990,,,,269990\nHW72JDRXX,2,2020-27634-05,,CTGCAACG,CGAATGTC,269990,,,,269990\nHW72JDRXX,2,2020-27636-05,,GATTCGAG,ATACTCGG,269990,,,,269990\nHW72JDRXX,2,2020-27668-05,,CTGATTGA,AGTGTGTC,269990,,,,269990\nHW72JDRXX,2,2020-27669-05,,TCGGTAAG,TGAGTTAG,269990,,,,269990\nHW72JDRXX,2,2020-27671-05,,TTAGAGTC,TCGTCACA,269990,,,,269990\nHW72JDRXX,2,2020-27710-05,,CCTGGTGT,CCGGAGGC,269990,,,,269990\nHW72JDRXX,2,2020-27725-05,,TGTGTTAA,ACCGTGCC,269990,,,,269990\nHW72JDRXX,2,2020-27726-05,,CCGCTGTT,TGCGGTCT,269990,,,,269990','2021-03-24 11:49:54'
```

**Review by barrystokman — APPROVED** [review]
👍🏻 

The auto-black made this much harder to review than strictly necessary 😦

**Comment by karlnyr** [comment]
Oh... That is very true. I applied black to the file due to it failing in Travis but I assume that the CI is not up to date or perfectly integrated.

**Comment by karlnyr** [comment]
Installed with the newest demux updates:
image

image

**Pull request merged**
